name: Deploy CCI Actions Demo
on:
  push:
    branches:
       kubectl-test
env:
  REGION_ID: 'cn-north-4'                  # set this to your preferred huaweicloud region, e.g. cn-north-4
  PROJECT_ID: '0f124b2f6400f3f12f91c005f1dc88b9'   # 项目ID，可以在华为云我的凭证获取
  ACCESS_KEY_ID: ${{ secrets.ACCESSKEY }}             # set this to your huaweicloud access-key-id
  ACCESS_KEY_SECRET: ${{ secrets.SECRETACCESSKEY }}               # set this to your huaweicloud access-key-secret
  SWR_ORGANIZATION:  'hdn'   # SWR 组织名
  IMAGE_NAME: 'cci'       # 镜像名称
            
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kubectl Tool Installer
        id: install-kubectl
        uses: Azure/setup-kubectl@v2.1

      - name: kubectl apply
        id: deploy-to-cci-by-devstar
        #uses: azure/webapps-deploy@v2
        run: |
          curl -LO "https://cci-iam-authenticator.obs.cn-north-4.myhuaweicloud.com/latest/linux-amd64/cci-iam-authenticator"
          chmod +x ./cci-iam-authenticator
          mv ./cci-iam-authenticator /usr/local/bin
          cci-iam-authenticator generate-kubeconfig --cci-endpoint=https://cci.cn-north-4.myhuaweicloud.com --ak=${{ secrets.ACCESSKEY }} --sk=${{ secrets.SECRETACCESSKEY }}
          kubectl get pods -n action-namespace-name-kubectl
